using System.Reflection;
#pragma warning disable CS7035 // The specified version string does not conform to the recommended format - major.minor.build.revision
// This code automatically generated by a template. Do not edit it directly.

// Version information for an assembly consists of the following four values:
//      Major Version
//      Minor Version
//      Build Number
//      Revision (Year (2 digit) + Days since start of year)
[assembly: AssemblyVersion("1.0.2")]
[assembly: AssemblyFileVersion("1.0.2.20160")]
[assembly: AssemblyInformationalVersion("1.0" +
#if DEBUG
    " DEBUG")]
#else
    "")]
#endif
